package gaming

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// ComposeServer is one game server or tool to write into a host's compose file.
type ComposeServer struct {
	Name     string
	Instance Instance
}

// HostCompose is the generated deployment for the servers on one host.
type HostCompose struct {
	// Compose is the docker-compose.yml; EnvExample lists the values to fill in.
	Compose    string
	EnvExample string
	// Skipped names the servers that have no container image, with the reason.
	Skipped []string
}

var (
	slugPattern        = regexp.MustCompile(`[^a-z0-9]+`)
	placeholderPattern = regexp.MustCompile(`\$\{([A-Za-z0-9_]+)\}`)
)

// composeServiceName turns a display name into a compose service key.
func composeServiceName(name string, used map[string]bool) string {
	base := strings.Trim(slugPattern.ReplaceAllString(strings.ToLower(name), "-"), "-")
	if base == "" {
		base = "server"
	}
	key := base
	for n := 2; used[key]; n++ {
		key = fmt.Sprintf("%s-%d", base, n)
	}
	used[key] = true
	return key
}

func yamlQuote(value string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(value) + `"`
}

// BuildHostCompose writes one compose file for the game servers on a host.
//
// A server that announces its own port (most Steam games) gets the same port
// inside and outside the container and is told the port through its variable.
// Any other server keeps its default port inside and is moved on the host side.
//
// Values the owner must supply become ${SERVICE_NAME} variables, prefixed with
// the service so two servers of the same game do not share a password.
func BuildHostCompose(hostName string, servers []ComposeServer) HostCompose {
	var compose, env strings.Builder
	result := HostCompose{}
	used := map[string]bool{}
	services := 0

	fmt.Fprintf(&compose, "# Game servers on %s\n# Generated by HLBuilder. Fill in .env before starting: docker compose up -d\n\nservices:\n", hostName)
	fmt.Fprintf(&env, "# Values for the game servers on %s. Copy to .env and fill in.\n", hostName)

	for _, server := range servers {
		instance, profile, err := server.Instance.Normalize()
		if err != nil {
			result.Skipped = append(result.Skipped, fmt.Sprintf("%s: %v", server.Name, err))
			continue
		}
		if profile.Image == "" {
			result.Skipped = append(result.Skipped, fmt.Sprintf("%s: %s", server.Name, profile.Notes))
			continue
		}
		services++
		key := composeServiceName(server.Name, used)
		prefix := strings.ToUpper(strings.ReplaceAll(key, "-", "_"))
		sizing := SizeServer(profile, instance.Players)
		ports := ResolvePorts(profile, instance.PortOffset)
		announces := profile.AnnouncesPorts()

		fmt.Fprintf(&compose, "  %s:\n    image: %s\n    container_name: %s\n    restart: unless-stopped\n", key, profile.Image, key)

		compose.WriteString("    ports:\n")
		for _, port := range ports {
			inside := port.Base
			if announces {
				inside = port.Port
			}
			fmt.Fprintf(&compose, "      - \"%d:%d/%s\"\n", port.Port, inside, port.Proto)
		}

		// Environment: fixed lines of the profile, then the port variables.
		variables := map[string]string{}
		order := []string{}
		set := func(name, value string) {
			if _, seen := variables[name]; !seen {
				order = append(order, name)
			}
			variables[name] = value
		}
		for _, line := range profile.Env {
			name, value, _ := strings.Cut(line, "=")
			value = strings.ReplaceAll(value, "{players}", fmt.Sprintf("%d", instance.Players))
			value = strings.ReplaceAll(value, "{ram_mb}", fmt.Sprintf("%d", sizing.RAMMB))
			value = placeholderPattern.ReplaceAllStringFunc(value, func(match string) string {
				variable := prefix + "_" + placeholderPattern.FindStringSubmatch(match)[1]
				fmt.Fprintf(&env, "%s=\n", variable)
				return "${" + variable + "}"
			})
			set(name, value)
		}
		if announces {
			for _, port := range ports {
				if port.Env != "" {
					set(port.Env, fmt.Sprintf("%d", port.Port))
				}
			}
		}
		if len(order) > 0 {
			compose.WriteString("    environment:\n")
			for _, name := range order {
				fmt.Fprintf(&compose, "      %s: %s\n", name, yamlQuote(variables[name]))
			}
		}

		if len(profile.Volumes) > 0 {
			compose.WriteString("    volumes:\n")
			for _, volume := range profile.Volumes {
				// Keep each server's data in its own folder next to the compose file.
				fmt.Fprintf(&compose, "      - %s\n", strings.Replace(volume, "./", "./"+key+"/", 1))
			}
		}
		compose.WriteString("\n")
	}

	sort.Strings(result.Skipped)
	if services == 0 {
		compose.Reset()
		fmt.Fprintf(&compose, "# Game servers on %s\n# None of the servers planned here has a container image.\n\nservices: {}\n", hostName)
	}
	if len(result.Skipped) > 0 {
		compose.WriteString("# Not included, install these by hand:\n")
		for _, line := range result.Skipped {
			fmt.Fprintf(&compose, "#   %s\n", line)
		}
	}
	result.Compose = compose.String()
	result.EnvExample = env.String()
	return result
}
