package gaming

// Catalog IDs continue the series the default service seed uses. Minecraft
// keeps the ID the original "Minecraft Server" entry had.
const serviceIDPrefix = "a1000000-0000-0000-0000-000000000"

func port(name string, number int, proto string, forward bool, env string) PortSpec {
	return PortSpec{Name: name, Port: number, Proto: proto, Forward: forward, Env: env}
}

// registry is ordered the way the catalog shows it: games first, then tools.
//
// Ports, images, variables and volumes were checked in October 2026 against
// each game's dedicated-server documentation and each image's own README.
// The per-player figures and the player counts are planning estimates: enough
// to tell a mini PC from a workstation, not a benchmark. MaxPlayers is a
// publisher limit only where the notes say so.
var registry = []Profile{
	{
		Slug: "minecraft_java", ServiceID: serviceIDPrefix + "011", Name: "Minecraft Java Server", Role: RoleGame,
		Description: "Minecraft Java Edition server. Paper is used by default for better performance with plugins.",
		Icon:        "minecraft", Website: "https://www.minecraft.net", Docs: "https://docker-minecraft-server.readthedocs.io",
		Tags:           []string{"game", "multiplayer", "java", "sandbox"},
		DefaultPlayers: 10, MaxPlayers: 100,
		BaseRAMMB: 2048, RAMMBPerPlayer: 100, BaseCPUCores: 1, CPUCoresPerPlayer: 0.05,
		StorageGB: 10, UploadKbpsPerPlayer: 120, SingleThread: true,
		Ports:   []PortSpec{port("game", 25565, "tcp", true, "")},
		Image:   "itzg/minecraft-server:latest",
		Env:     []string{"EULA=TRUE", "TYPE=PAPER", "MEMORY={ram_mb}M", "MAX_PLAYERS={players}"},
		Volumes: []string{"./data:/data"},
		Notes:   "The world tick runs on one core, so a fast core beats many slow ones. Memory grows with view distance and world size.",
	},
	{
		Slug: "minecraft_bedrock", ServiceID: serviceIDPrefix + "101", Name: "Minecraft Bedrock Server", Role: RoleGame,
		Description: "Minecraft Bedrock Edition server for consoles, phones and Windows clients.",
		Icon:        "minecraft", Website: "https://www.minecraft.net/download/server/bedrock", Docs: "https://github.com/itzg/docker-minecraft-bedrock-server",
		Tags:           []string{"game", "multiplayer", "bedrock", "console"},
		DefaultPlayers: 10, MaxPlayers: 30,
		BaseRAMMB: 1024, RAMMBPerPlayer: 60, BaseCPUCores: 1, CPUCoresPerPlayer: 0.05,
		StorageGB: 5, UploadKbpsPerPlayer: 120, SingleThread: true,
		Ports: []PortSpec{
			port("game", 19132, "udp", true, ""),
			port("game-ipv6", 19133, "udp", false, ""),
		},
		Image:   "itzg/minecraft-bedrock-server:latest",
		Env:     []string{"EULA=TRUE", "MAX_PLAYERS={players}"},
		Volumes: []string{"./data:/data"},
		Notes:   "Consoles find LAN servers by broadcast on UDP 19132, so keep the default port for a LAN party. Port 19133 is only for IPv6 clients.",
	},
	{
		Slug: "valheim", ServiceID: serviceIDPrefix + "102", Name: "Valheim Server", Role: RoleGame,
		Description: "Dedicated server for Valheim worlds shared by a small group.",
		Icon:        "valheim", Website: "https://www.valheimgame.com", Docs: "https://github.com/community-valheim-tools/valheim-server-docker",
		Tags:           []string{"game", "multiplayer", "survival", "steam"},
		DefaultPlayers: 5, MaxPlayers: 10,
		BaseRAMMB: 3072, RAMMBPerPlayer: 150, BaseCPUCores: 1.5, CPUCoresPerPlayer: 0.1,
		StorageGB: 5, UploadKbpsPerPlayer: 150, SingleThread: true,
		Ports: []PortSpec{
			port("game", 2456, "udp", true, "SERVER_PORT"),
			port("query", 2457, "udp", true, ""),
		},
		Image:   "ghcr.io/community-valheim-tools/valheim-server:latest",
		Env:     []string{"SERVER_NAME=${SERVER_NAME}", "WORLD_NAME=${WORLD_NAME}", "SERVER_PASS=${SERVER_PASS}"},
		Volumes: []string{"./config:/config", "./server:/opt/valheim"},
		Notes:   "The server uses its port and the one above it. The password needs at least 5 characters. Crossplay goes through a relay and needs no port forward.",
	},
	{
		Slug: "palworld", ServiceID: serviceIDPrefix + "103", Name: "Palworld Server", Role: RoleGame,
		Description: "Dedicated server for Palworld. The publisher recommends 16 GB of memory.",
		Icon:        "palworld", Website: "https://www.pocketpair.jp/palworld", Docs: "https://github.com/thijsvanloef/palworld-server-docker",
		Tags:           []string{"game", "multiplayer", "survival", "steam"},
		DefaultPlayers: 8, MaxPlayers: 32,
		BaseRAMMB: 14336, RAMMBPerPlayer: 128, BaseCPUCores: 2, CPUCoresPerPlayer: 0.15,
		StorageGB: 20, UploadKbpsPerPlayer: 200,
		Ports: []PortSpec{
			port("game", 8211, "udp", true, "PORT"),
			port("query", 27015, "udp", false, "QUERY_PORT"),
		},
		Image:   "thijsvanloef/palworld-server-docker:latest",
		Env:     []string{"PLAYERS={players}", "SERVER_PASSWORD=${SERVER_PASSWORD}", "ADMIN_PASSWORD=${ADMIN_PASSWORD}"},
		Volumes: []string{"./palworld:/palworld"},
		Notes:   "With 8 GB the server starts but is likely to crash. The query port is only needed to appear in the community server list.",
	},
	{
		Slug: "cs2", ServiceID: serviceIDPrefix + "104", Name: "Counter-Strike 2 Server", Role: RoleGame,
		Description: "Dedicated Counter-Strike 2 server for scrims and LAN tournaments.",
		Icon:        "counter-strike", Website: "https://www.counter-strike.net", Docs: "https://github.com/joedwards32/CS2",
		Tags:           []string{"game", "multiplayer", "fps", "steam", "lan-party"},
		DefaultPlayers: 10, MaxPlayers: 64,
		BaseRAMMB: 2048, RAMMBPerPlayer: 64, BaseCPUCores: 2, CPUCoresPerPlayer: 0.05,
		StorageGB: 65, UploadKbpsPerPlayer: 250, SingleThread: true,
		Ports: []PortSpec{
			port("game", 27015, "udp", true, "CS2_PORT"),
			port("rcon", 27015, "tcp", false, "CS2_PORT"),
			port("tv", 27020, "udp", false, "TV_PORT"),
		},
		Image:   "joedwards32/cs2:latest",
		Env:     []string{"SRCDS_TOKEN=${SRCDS_TOKEN}", "CS2_SERVERNAME=${CS2_SERVERNAME}", "CS2_RCONPW=${CS2_RCONPW}", "CS2_PW=${CS2_PW}", "CS2_MAXPLAYERS={players}"},
		Volumes: []string{"./cs2:/home/steam/cs2-dedicated"},
		Notes:   "Players outside the LAN can only join when SRCDS_TOKEN holds a Steam game server login token. The game files take about 65 GB.",
	},
	{
		Slug: "terraria", ServiceID: serviceIDPrefix + "105", Name: "Terraria Server", Role: RoleGame,
		Description: "Terraria server with TShock for moderation and plugins.",
		Icon:        "terraria", Website: "https://terraria.org", Docs: "https://github.com/ryansheehan/terraria",
		Tags:           []string{"game", "multiplayer", "sandbox"},
		DefaultPlayers: 8, MaxPlayers: 255,
		BaseRAMMB: 768, RAMMBPerPlayer: 64, BaseCPUCores: 0.5, CPUCoresPerPlayer: 0.05,
		StorageGB: 2, UploadKbpsPerPlayer: 60, SingleThread: true,
		Ports:   []PortSpec{port("game", 7777, "tcp", true, "")},
		Image:   "ryshe/terraria:latest",
		Volumes: []string{"./worlds:/root/.local/share/Terraria/Worlds"},
		Notes:   "The game allows up to 255 players. Light enough for a Raspberry Pi with a small world.",
	},
	{
		Slug: "factorio", ServiceID: serviceIDPrefix + "106", Name: "Factorio Server", Role: RoleGame,
		Description: "Headless Factorio server. Every client simulates the whole factory, so the slowest PC sets the pace.",
		Icon:        "factorio", Website: "https://www.factorio.com", Docs: "https://github.com/factoriotools/factorio-docker",
		Tags:           []string{"game", "multiplayer", "automation"},
		DefaultPlayers: 8, MaxPlayers: 64,
		BaseRAMMB: 1024, RAMMBPerPlayer: 32, BaseCPUCores: 1, CPUCoresPerPlayer: 0.02,
		StorageGB: 4, UploadKbpsPerPlayer: 60, SingleThread: true,
		Ports: []PortSpec{
			port("game", 34197, "udp", true, "PORT"),
			port("rcon", 27015, "tcp", false, "RCON_PORT"),
		},
		Image:   "factoriotools/factorio:stable",
		Volumes: []string{"./factorio:/factorio"},
		Notes:   "Factorio uses UDP only. Large late-game factories need far more memory than the base figure.",
	},
	{
		Slug: "satisfactory", ServiceID: serviceIDPrefix + "107", Name: "Satisfactory Server", Role: RoleGame,
		Description: "Dedicated server for Satisfactory factories shared with a few friends.",
		Icon:        "satisfactory", Website: "https://www.satisfactorygame.com", Docs: "https://github.com/wolveix/satisfactory-server",
		Tags:           []string{"game", "multiplayer", "automation", "steam"},
		DefaultPlayers: 4, MaxPlayers: 8,
		BaseRAMMB: 8192, RAMMBPerPlayer: 512, BaseCPUCores: 2, CPUCoresPerPlayer: 0.25,
		StorageGB: 20, UploadKbpsPerPlayer: 250,
		Ports: []PortSpec{
			port("game", 7777, "udp", true, "SERVERGAMEPORT"),
			port("api", 7777, "tcp", true, "SERVERGAMEPORT"),
			port("messaging", 8888, "tcp", true, "SERVERMESSAGINGPORT"),
		},
		Image:   "wolveix/satisfactory-server:latest",
		Env:     []string{"MAXPLAYERS={players}"},
		Volumes: []string{"./config:/config"},
		Notes:   "The server is set up for 4 players; the publisher suggests 16 GB for more. The same port number carries UDP game traffic and the TCP server API: forward both.",
	},
	{
		Slug: "rust", ServiceID: serviceIDPrefix + "108", Name: "Rust Server", Role: RoleGame,
		Description: "Dedicated Rust server. Map size drives memory more than the player count.",
		Icon:        "rust", Website: "https://rust.facepunch.com", Docs: "https://github.com/Didstopia/rust-server",
		Tags:           []string{"game", "multiplayer", "survival", "steam"},
		DefaultPlayers: 20, MaxPlayers: 200,
		BaseRAMMB: 11264, RAMMBPerPlayer: 48, BaseCPUCores: 2, CPUCoresPerPlayer: 0.04,
		StorageGB: 30, UploadKbpsPerPlayer: 250, SingleThread: true,
		Ports: []PortSpec{
			port("game", 28015, "udp", true, "RUST_SERVER_PORT"),
			port("query", 28017, "udp", true, "RUST_SERVER_QUERYPORT"),
			port("rcon", 28016, "tcp", false, "RUST_RCON_PORT"),
			port("rust-plus", 28082, "tcp", false, "RUST_APP_PORT"),
		},
		Image:   "didstopia/rust-server:latest",
		Env:     []string{"RUST_SERVER_NAME=${RUST_SERVER_NAME}", "RUST_SERVER_MAXPLAYERS={players}", "RUST_RCON_PASSWORD=${RUST_RCON_PASSWORD}"},
		Volumes: []string{"./rust:/steamcmd/rust"},
		Notes:   "The publisher asks for 12 GB of free memory, more for a 6000-size map. Forward the Rust+ port only if players use the companion app.",
	},
	{
		Slug: "ark_se", ServiceID: serviceIDPrefix + "109", Name: "ARK: Survival Evolved Server", Role: RoleGame,
		Description: "Dedicated server for ARK: Survival Evolved. Memory use depends heavily on the map.",
		Icon:        "ark", Website: "https://www.playark.com", Docs: "https://github.com/Hermsi1337/docker-ark-server",
		Tags:           []string{"game", "multiplayer", "survival", "steam"},
		DefaultPlayers: 10, MaxPlayers: 70,
		BaseRAMMB: 8192, RAMMBPerPlayer: 128, BaseCPUCores: 2, CPUCoresPerPlayer: 0.08,
		StorageGB: 40, UploadKbpsPerPlayer: 250, SingleThread: true,
		Ports: []PortSpec{
			port("game", 7777, "udp", true, "GAME_CLIENT_PORT"),
			port("peer", 7778, "udp", true, "UDP_SOCKET_PORT"),
			port("query", 27015, "udp", true, "SERVER_LIST_PORT"),
			port("rcon", 27020, "tcp", false, "RCON_PORT"),
		},
		Image:   "hermsi/ark-server:latest",
		Env:     []string{"SESSION_NAME=${SESSION_NAME}", "SERVER_MAP=${SERVER_MAP}", "SERVER_PASSWORD=${SERVER_PASSWORD}", "ADMIN_PASSWORD=${ADMIN_PASSWORD}", "MAX_PLAYERS={players}"},
		Volumes: []string{"./ark:/app"},
		Notes:   "An empty server uses 3 to 12 GB depending on the map. Each extra map is another server of this size. ARK: Survival Ascended has no native Linux server and needs about 16 GB per map.",
	},
	{
		Slug: "project_zomboid", ServiceID: serviceIDPrefix + "110", Name: "Project Zomboid Server", Role: RoleGame,
		Description: "Dedicated server for Project Zomboid co-op survival.",
		Icon:        "project-zomboid", Website: "https://projectzomboid.com", Docs: "https://github.com/Danixu/project-zomboid-server-docker",
		Tags:           []string{"game", "multiplayer", "survival", "steam"},
		DefaultPlayers: 8, MaxPlayers: 32,
		BaseRAMMB: 2048, RAMMBPerPlayer: 512, BaseCPUCores: 1.5, CPUCoresPerPlayer: 0.1,
		StorageGB: 10, UploadKbpsPerPlayer: 150,
		Ports: []PortSpec{
			port("game", 16261, "udp", true, "PORT"),
			port("direct", 16262, "udp", true, "UDPPORT"),
		},
		Image:   "danixu86/project-zomboid-dedicated-server:latest",
		Env:     []string{"SERVERNAME=${SERVERNAME}", "ADMINPASSWORD=${ADMINPASSWORD}", "PASSWORD=${PASSWORD}"},
		Volumes: []string{"./zomboid:/home/steam/Zomboid"},
		Notes:   "The admin password is required on the first start. Mods add to the memory figure quickly.",
	},
	{
		Slug: "seven_days_to_die", ServiceID: serviceIDPrefix + "111", Name: "7 Days to Die Server", Role: RoleGame,
		Description: "Dedicated server for 7 Days to Die. The game supports up to 8 players.",
		Icon:        "7-days-to-die", Website: "https://7daystodie.com", Docs: "https://developer.valvesoftware.com/wiki/7_Days_to_Die_Dedicated_Server",
		Tags:           []string{"game", "multiplayer", "survival", "steam"},
		DefaultPlayers: 8, MaxPlayers: 8,
		BaseRAMMB: 6144, RAMMBPerPlayer: 256, BaseCPUCores: 2, CPUCoresPerPlayer: 0.15,
		StorageGB: 20, UploadKbpsPerPlayer: 200,
		Ports: []PortSpec{
			port("game", 26900, "tcp", true, ""),
			port("game", 26900, "udp", true, ""),
			port("net1", 26901, "udp", true, ""),
			port("net2", 26902, "udp", true, ""),
			port("net3", 26903, "udp", true, ""),
		},
		Notes: "No container image is suggested: the ports are set in the server's own config file, not by a variable. Install with SteamCMD (app 294420) or LinuxGSM on a VM.",
	},
	{
		Slug: "enshrouded", ServiceID: serviceIDPrefix + "112", Name: "Enshrouded Server", Role: RoleGame,
		Description: "Dedicated server for Enshrouded, up to 16 players. The publisher asks for 16 GB of memory.",
		Icon:        "enshrouded", Website: "https://enshrouded.com", Docs: "https://github.com/mornedhels/enshrouded-server",
		Tags:           []string{"game", "multiplayer", "survival", "steam"},
		DefaultPlayers: 6, MaxPlayers: 16,
		BaseRAMMB: 14336, RAMMBPerPlayer: 128, BaseCPUCores: 2, CPUCoresPerPlayer: 0.25,
		StorageGB: 30, UploadKbpsPerPlayer: 250,
		Ports:   []PortSpec{port("query", 15637, "udp", true, "SERVER_QUERYPORT")},
		Image:   "mornedhels/enshrouded-server:latest",
		Env:     []string{"SERVER_NAME=${SERVER_NAME}", "SERVER_SLOT_COUNT={players}"},
		Volumes: []string{"./enshrouded:/opt/enshrouded"},
		Notes:   "16 players is the game's limit. The server is a Windows program that the image runs through Proton. Passwords are set through server roles in the config file.",
	},
	{
		Slug: "v_rising", ServiceID: serviceIDPrefix + "113", Name: "V Rising Server", Role: RoleGame,
		Description: "Dedicated server for V Rising clans.",
		Icon:        "v-rising", Website: "https://playvrising.com", Docs: "https://github.com/StunlockStudios/vrising-dedicated-server-instructions",
		Tags:           []string{"game", "multiplayer", "survival", "steam"},
		DefaultPlayers: 10, MaxPlayers: 40,
		BaseRAMMB: 6144, RAMMBPerPlayer: 160, BaseCPUCores: 2, CPUCoresPerPlayer: 0.08,
		StorageGB: 15, UploadKbpsPerPlayer: 200,
		Ports: []PortSpec{
			port("game", 9876, "udp", true, ""),
			port("query", 9877, "udp", false, ""),
		},
		Notes: "No container image is suggested: the server is a Windows program and the community images need manual fixes. The ports shown are the usual choice; the query port is only needed to appear in the server list.",
	},

	// ── Tools ────────────────────────────────────────────────────────────────
	{
		Slug: "lancache", ServiceID: serviceIDPrefix + "201", Name: "LANCache", Role: RoleTool,
		Description: "Caches game downloads from Steam, Epic, Battle.net and others, so the second PC installs at LAN speed.",
		Icon:        "lancache", Website: "https://lancache.net", Docs: "https://lancache.net/docs/",
		Tags:      []string{"cache", "lan-party", "downloads", "steam"},
		BaseRAMMB: 2048, BaseCPUCores: 1, StorageGB: 500,
		Ports: []PortSpec{
			port("http", 80, "tcp", false, ""),
			port("https", 443, "tcp", false, ""),
		},
		Image:   "lancachenet/monolithic:latest",
		Env:     []string{"CACHE_DISK_SIZE=${CACHE_DISK_SIZE}", "UPSTREAM_DNS=${UPSTREAM_DNS}"},
		Volumes: []string{"./cache:/data/cache", "./logs:/data/logs"},
		Notes:   "Clients must use a DNS server that points game CDNs at the cache: run lancachenet/lancache-dns next to it, or add overrides on your own DNS. Nothing is forwarded from the internet. Give it the fastest link you have.",
	},
	{
		Slug: "pelican_panel", ServiceID: serviceIDPrefix + "202", Name: "Pelican Panel", Role: RoleTool,
		Description: "Web panel for running many game servers in containers, the successor to Pterodactyl.",
		Icon:        "pelican", Website: "https://pelican.dev", Docs: "https://pelican.dev/docs/",
		Tags:      []string{"panel", "management", "game-servers"},
		BaseRAMMB: 1024, BaseCPUCores: 1, StorageGB: 5,
		Ports: []PortSpec{
			port("http", 80, "tcp", false, ""),
			port("https", 443, "tcp", false, ""),
		},
		Image:   "ghcr.io/pelican/panel:latest",
		Env:     []string{"APP_URL=${APP_URL}", "XDG_DATA_HOME=/pelican-data"},
		Volumes: []string{"./pelican-data:/pelican-data", "./pelican-logs:/var/www/html/storage/logs"},
		Notes:   "The panel only manages servers. The Wings agent on each host runs them; it listens on 8080 and 2022 and needs the game ports.",
	},
	{
		Slug: "crafty_controller", ServiceID: serviceIDPrefix + "203", Name: "Crafty Controller", Role: RoleTool,
		Description: "Web panel for creating, starting and backing up Minecraft servers.",
		Icon:        "crafty", Website: "https://craftycontrol.com", Docs: "https://docs.craftycontrol.com",
		Tags:      []string{"panel", "management", "minecraft"},
		BaseRAMMB: 1024, BaseCPUCores: 1, StorageGB: 10,
		Ports:   []PortSpec{port("https", 8443, "tcp", false, "")},
		Image:   "registry.gitlab.com/crafty-controller/crafty-4:latest",
		Volumes: []string{"./backups:/crafty/backups", "./logs:/crafty/logs", "./servers:/crafty/servers", "./config:/crafty/app/config", "./import:/crafty/import"},
		Notes:   "Size the host for the Minecraft servers it will run, not for the panel. The servers it starts use ports 25500 to 25600.",
	},
	{
		Slug: "mumble", ServiceID: serviceIDPrefix + "204", Name: "Mumble Server", Role: RoleTool,
		Description: "Low-latency open-source voice chat.",
		Icon:        "mumble", Website: "https://www.mumble.info", Docs: "https://github.com/mumble-voip/mumble-docker",
		Tags:           []string{"voice", "chat", "open-source"},
		DefaultPlayers: 10, MaxPlayers: 100,
		BaseRAMMB: 128, RAMMBPerPlayer: 4, BaseCPUCores: 0.5, CPUCoresPerPlayer: 0.01,
		StorageGB: 1, UploadKbpsPerPlayer: 60,
		Ports: []PortSpec{
			port("voice", 64738, "udp", true, ""),
			port("control", 64738, "tcp", true, ""),
		},
		Image:   "mumblevoip/mumble-server:latest",
		Env:     []string{"MUMBLE_SUPERUSER_PASSWORD=${MUMBLE_SUPERUSER_PASSWORD}"},
		Volumes: []string{"./data:/data"},
	},
	{
		Slug: "teamspeak", ServiceID: serviceIDPrefix + "205", Name: "TeamSpeak 3 Server", Role: RoleTool,
		Description: "Voice chat server. Without a licence file it allows 32 slots.",
		Icon:        "teamspeak", Website: "https://www.teamspeak.com", Docs: "https://hub.docker.com/_/teamspeak",
		Tags:           []string{"voice", "chat"},
		DefaultPlayers: 10, MaxPlayers: 32,
		BaseRAMMB: 256, RAMMBPerPlayer: 4, BaseCPUCores: 0.5, CPUCoresPerPlayer: 0.01,
		StorageGB: 1, UploadKbpsPerPlayer: 60,
		Ports: []PortSpec{
			port("voice", 9987, "udp", true, ""),
			port("files", 30033, "tcp", true, ""),
			port("query", 10011, "tcp", false, ""),
		},
		Image:   "teamspeak:latest",
		Env:     []string{"TS3SERVER_LICENSE=accept"},
		Volumes: []string{"./data:/var/ts3server"},
		Notes:   "Keep the query port private.",
	},
}
