/**
 * The configs the Config Generator page writes itself. Compose, .env, the
 * Ansible inventory and Nginx come from the backend (buildApi.generateConfig).
 */

import type { HardwareNode } from '../../../types'

/** A service as these generators need it: only its name. */
type NamedService = { name: string }

// ─── Service ports ────────────────────────────────────────────────────────────
/** The port a known service listens on inside its container. */
const SERVICE_PORTS: Record<string, string> = {
    'Plex': '32400',
    'Jellyfin': '8096',
    'Sonarr': '8989',
    'Radarr': '7878',
    'Prowlarr': '9696',
    'qBittorrent': '8080',
    'Portainer': '9000',
    'Nginx Proxy Manager': '80',
    'Traefik': '80',
    'Grafana': '3000',
    'Prometheus': '9090',
    'Home Assistant': '8123',
    'Nextcloud': '80',
    'Vaultwarden': '80',
    'Gitea': '3000',
    'Pi-hole': '53/tcp',
    'AdGuard Home': '53/tcp',
    'Uptime Kuma': '3001',
    'Immich': '3001',
    'Paperless-ngx': '8000',
}

function servicePort(name: string): string {
    // Try exact match, then partial match
    if (SERVICE_PORTS[name]) return SERVICE_PORTS[name]
    const key = Object.keys(SERVICE_PORTS).find(k => name.toLowerCase().includes(k.toLowerCase()) || k.toLowerCase().includes(name.toLowerCase()))
    return key ? SERVICE_PORTS[key] : '8080'
}

// ─── IP plan ──────────────────────────────────────────────────────────────────
export function generateIpPlan(nodes: HardwareNode[]): string {
    const lines: string[] = [
        '# IP Address Plan (Calculated by Backend)',
        `# Generated: ${new Date().toISOString()}`,
        '',
        'Name'.padEnd(30) + 'IP Address'.padEnd(20) + 'Type',
        '-'.repeat(70)
    ]

    const allItems: { name: string, ip: string, type: string }[] = []

    nodes.forEach(n => {
        if (n.ip) allItems.push({ name: n.name, ip: n.ip, type: n.type })
        n.vms?.forEach(vm => {
            if (vm.ip) allItems.push({ name: vm.name, ip: vm.ip, type: vm.type })
        })
    })

    // Sort by IP
    allItems.sort((a, b) => {
        const ipA = a.ip.split('.').map(Number);
        const ipB = b.ip.split('.').map(Number);
        for (let i = 0; i < 4; i++) {
            if (ipA[i] !== ipB[i]) return ipA[i] - ipB[i];
        }
        return 0;
    });

    allItems.forEach(item => {
        lines.push(`${item.name.padEnd(30)}${item.ip.padEnd(20)}${item.type}`)
    })

    return lines.join('\n')
}

// ─── Ansible Playbook ─────────────────────────────────────────────────────────
export function generateAnsiblePlaybook(services: NamedService[]): string {
    const lines: string[] = [
        '# Generated by HLBuilder',
        `# Generated: ${new Date().toISOString()}`,
        '',
        '---',
        '- name: Homelab Setup',
        '  hosts: homelab',
        '  become: true',
        '  vars:',
        '    docker_compose_dir: /opt/homelab',
        '',
        '  tasks:',
        '    - name: Install Docker',
        '      apt:',
        '        name:',
        '          - docker.io',
        '          - docker-compose-plugin',
        '        state: present',
        '        update_cache: yes',
        '',
        '    - name: Start Docker service',
        '      service:',
        '        name: docker',
        '        state: started',
        '        enabled: yes',
        '',
        '    - name: Create homelab directory',
        '      file:',
        '        path: "{{ docker_compose_dir }}"',
        '        state: directory',
        '        mode: \'0755\'',
        '',
        '    - name: Copy docker-compose.yml',
        '      copy:',
        '        src: docker-compose.yml',
        '        dest: "{{ docker_compose_dir }}/docker-compose.yml"',
        '',
        '    - name: Copy .env file',
        '      copy:',
        '        src: .env',
        '        dest: "{{ docker_compose_dir }}/.env"',
        '        mode: \'0600\'',
        '',
        '    - name: Start services',
        '      community.docker.docker_compose_v2:',
        '        project_src: "{{ docker_compose_dir }}"',
        '        state: present',
        '',
    ]

    if (services.length > 0) {
        lines.push('    # ── Service-specific tasks ──────────────────────────────────────────')
        services.forEach(svc => {
            lines.push(`    - name: Ensure ${svc.name} is running`)
            lines.push(`      community.docker.docker_container_info:`)
            lines.push(`        name: ${svc.name.toLowerCase().replace(/[^a-z0-9]/g, '_')}`)
            lines.push(`      register: ${svc.name.toLowerCase().replace(/[^a-z0-9]/g, '_')}_info`)
            lines.push('')
        })
    }

    return lines.join('\n')
}

// ─── Traefik Labels Generator ─────────────────────────────────────────────────
export function generateTraefikLabels(services: NamedService[], domain = 'homelab.local'): string {
    const lines: string[] = [
        '# Generated by HLBuilder - Traefik labels',
        `# Generated: ${new Date().toISOString()}`,
        '# Add these labels to each service in your docker-compose.yml',
        '',
    ]

    services.forEach(svc => {
        const slug = svc.name.toLowerCase().replace(/[^a-z0-9]/g, '-')
        const port = servicePort(svc.name)
        lines.push(`# ── ${svc.name}`)
        lines.push(`labels:`)
        lines.push(`  - "traefik.enable=true"`)
        lines.push(`  - "traefik.http.routers.${slug}.rule=Host(\`${slug}.${domain}\`)"`)
        lines.push(`  - "traefik.http.routers.${slug}.entrypoints=websecure"`)
        lines.push(`  - "traefik.http.routers.${slug}.tls.certresolver=letsencrypt"`)
        lines.push(`  - "traefik.http.services.${slug}.loadbalancer.server.port=${port}"`)
        lines.push('')
    })

    return lines.join('\n')
}
