package services

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/Butterski/homelab-builder/backend/internal/llm"
	"github.com/Butterski/homelab-builder/backend/internal/models"
	"github.com/Butterski/homelab-builder/backend/internal/secrets"
	"github.com/google/uuid"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const (
	systemSecretsKeySetting = "assistant_secrets_key"
	// databaseKeyVersion marks keys sealed with the master key an instance
	// generated for itself, as opposed to one supplied through SECRETS_KEY.
	databaseKeyVersion = 0

	maxProviderKeyLength = 500
	maxModelNameLength   = 200
)

var (
	// ErrAssistantUnavailable means the instance has the assistant switched off.
	ErrAssistantUnavailable = errors.New("the assistant is not available on this instance")
	// ErrAssistantDisabled means the user has not turned the assistant on.
	ErrAssistantDisabled = errors.New("the assistant is turned off in your settings")
	// ErrAssistantNotConfigured means a provider, model or key is still missing.
	ErrAssistantNotConfigured = errors.New("the assistant is not fully set up")
	// ErrAssistantKeyUnusable means the stored key can no longer be decrypted.
	ErrAssistantKeyUnusable = errors.New("the stored API key can no longer be read; enter it again in Settings")
	// ErrAssistantInput marks invalid settings.
	ErrAssistantInput = errors.New("invalid assistant settings")
)

// LoadKeyring returns the master key that protects stored provider keys.
//
// With SECRETS_KEY set, that key is used and never touches the database. Without
// it, an instance generates a key once and keeps it in its own database: stored
// provider keys are then safe in a leaked table dump or backup of that one
// table, but not from someone who can read the whole database. A public
// instance therefore must set SECRETS_KEY (requireEnvKey).
func LoadKeyring(db *gorm.DB, secretsKey string, version int, requireEnvKey bool) (*secrets.Keyring, error) {
	if secretsKey != "" {
		key, err := secrets.ParseKey(secretsKey)
		if err != nil {
			return nil, fmt.Errorf("SECRETS_KEY: %w (generate one with: openssl rand -base64 32)", err)
		}
		return secrets.NewKeyring(version, key, secrets.SourceEnv)
	}
	if requireEnvKey {
		return nil, errors.New("SECRETS_KEY is required to store provider keys on this instance (generate one with: openssl rand -base64 32), or set ASSISTANT_ENABLED=false")
	}

	var setting models.SystemSetting
	err := db.First(&setting, "key = ?", systemSecretsKeySetting).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		generated, genErr := secrets.GenerateKey()
		if genErr != nil {
			return nil, genErr
		}
		// Another instance may be starting at the same moment: keep whichever key landed first.
		if err := db.Clauses(clause.OnConflict{DoNothing: true}).
			Create(&models.SystemSetting{Key: systemSecretsKeySetting, Value: generated}).Error; err != nil {
			return nil, err
		}
		err = db.First(&setting, "key = ?", systemSecretsKeySetting).Error
	}
	if err != nil {
		return nil, err
	}
	key, err := secrets.ParseKey(setting.Value)
	if err != nil {
		return nil, fmt.Errorf("stored secrets key: %w", err)
	}
	return secrets.NewKeyring(databaseKeyVersion, key, secrets.SourceDatabase)
}

// AssistantSettingsService stores each user's assistant configuration. The
// provider key is encrypted before it is written and never leaves this service
// except through ResolveCredentials, for the duration of one chat request.
type AssistantSettingsService struct {
	db           *gorm.DB
	keyring      *secrets.Keyring
	available    bool
	allowPrivate bool
}

// NewAssistantSettingsService wires the service. available is the instance-wide
// switch; allowPrivate lets custom endpoints point at private addresses.
func NewAssistantSettingsService(db *gorm.DB, keyring *secrets.Keyring, available, allowPrivate bool) *AssistantSettingsService {
	return &AssistantSettingsService{db: db, keyring: keyring, available: available && keyring != nil, allowPrivate: allowPrivate}
}

// KeyStorageView shows exactly how a stored key is held, so users can see it is
// encrypted rather than take our word for it. It contains no secret material:
// the preview is ciphertext.
type KeyStorageView struct {
	Algorithm string `json:"algorithm"`
	// MasterKeySource is "env" (SECRETS_KEY, kept outside the database) or
	// "database" (generated by the instance and stored in its own database).
	MasterKeySource   string     `json:"master_key_source"`
	MasterKeyVersion  int        `json:"master_key_version"`
	NonceHex          string     `json:"nonce_hex"`
	CiphertextBytes   int        `json:"ciphertext_bytes"`
	CiphertextPreview string     `json:"ciphertext_preview"`
	CiphertextSHA256  string     `json:"ciphertext_sha256"`
	BoundTo           string     `json:"bound_to"`
	StoredAt          *time.Time `json:"stored_at"`
	LastUsedAt        *time.Time `json:"last_used_at"`
}

// AssistantSettingsView is what the settings page receives. It never contains the key.
type AssistantSettingsView struct {
	// Available is false when the instance operator switched the assistant off.
	Available bool   `json:"available"`
	Enabled   bool   `json:"enabled"`
	Provider  string `json:"provider"`
	Model     string `json:"model"`
	BaseURL   string `json:"base_url"`
	HasKey    bool   `json:"has_key"`
	// KeyHint is the last four characters of the key, for recognising it.
	KeyHint string `json:"key_hint"`
	// KeyUsable is false when the key was sealed with a master key the instance
	// no longer has; it then has to be entered again.
	KeyUsable  bool            `json:"key_usable"`
	KeyStorage *KeyStorageView `json:"key_storage"`
	// Ready means a chat can start: enabled, provider, model and key are in place.
	Ready                 bool         `json:"ready"`
	Providers             []llm.Preset `json:"providers"`
	AllowPrivateEndpoints bool         `json:"allow_private_endpoints"`
	MasterKeySource       string       `json:"master_key_source"`
}

// UpdateAssistantSettingsInput changes the fields that are set. APIKey is
// write-only: it can be replaced or removed, never read back.
type UpdateAssistantSettingsInput struct {
	Enabled  *bool   `json:"enabled"`
	Provider *string `json:"provider"`
	Model    *string `json:"model"`
	BaseURL  *string `json:"base_url"`
	APIKey   *string `json:"api_key"`
}

// AssistantCredentials is a resolved configuration with the decrypted key.
// It must not be stored, logged or returned to a client.
type AssistantCredentials struct {
	Provider string
	Model    string
	BaseURL  string
	APIKey   string
}

// keyAAD binds a sealed key to its owner: a ciphertext copied into another
// account's row fails authentication instead of decrypting.
func keyAAD(userID uuid.UUID) []byte {
	return []byte("hlb:assistant-key:v1|user:" + userID.String())
}

func (s *AssistantSettingsService) load(userID uuid.UUID) (*models.AssistantSettings, error) {
	var settings models.AssistantSettings
	err := s.db.First(&settings, "user_id = ?", userID).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return &models.AssistantSettings{UserID: userID}, nil
	}
	if err != nil {
		return nil, err
	}
	return &settings, nil
}

func (s *AssistantSettingsService) keyUsable(settings *models.AssistantSettings) bool {
	if len(settings.KeyCiphertext) == 0 || s.keyring == nil {
		return false
	}
	_, err := s.keyring.Open(settings.KeyCiphertext, settings.KeyNonce, settings.KeyVersion, keyAAD(settings.UserID))
	return err == nil
}

func (s *AssistantSettingsService) ready(settings *models.AssistantSettings, usable bool) bool {
	preset, ok := llm.PresetByID(settings.Provider)
	if !ok || !s.available || !settings.Enabled || strings.TrimSpace(settings.Model) == "" {
		return false
	}
	if preset.KeyRequired && !usable {
		return false
	}
	// A key that is stored but unreadable would fail mid-chat; ask for it again instead.
	if len(settings.KeyCiphertext) > 0 && !usable {
		return false
	}
	if !preset.CustomBaseURL {
		return true
	}
	_, err := llm.ValidateBaseURL(settings.BaseURL, s.allowPrivate)
	return err == nil
}

func (s *AssistantSettingsService) view(settings *models.AssistantSettings) *AssistantSettingsView {
	usable := s.keyUsable(settings)
	view := &AssistantSettingsView{
		Available: s.available, Enabled: settings.Enabled && s.available,
		Provider: settings.Provider, Model: settings.Model, BaseURL: settings.BaseURL,
		HasKey: len(settings.KeyCiphertext) > 0, KeyHint: settings.KeyHint, KeyUsable: usable,
		Ready:     s.ready(settings, usable),
		Providers: llm.Presets, AllowPrivateEndpoints: s.allowPrivate,
	}
	if s.keyring != nil {
		view.MasterKeySource = s.keyring.Source
	}
	if view.HasKey {
		digest := sha256.Sum256(settings.KeyCiphertext)
		preview := settings.KeyCiphertext
		if len(preview) > 12 {
			preview = preview[:12]
		}
		source := secrets.SourceEnv
		if settings.KeyVersion == databaseKeyVersion {
			source = secrets.SourceDatabase
		}
		view.KeyStorage = &KeyStorageView{
			Algorithm:         secrets.Algorithm,
			MasterKeySource:   source,
			MasterKeyVersion:  settings.KeyVersion,
			NonceHex:          hex.EncodeToString(settings.KeyNonce),
			CiphertextBytes:   len(settings.KeyCiphertext),
			CiphertextPreview: hex.EncodeToString(preview),
			CiphertextSHA256:  hex.EncodeToString(digest[:8]),
			BoundTo:           "your account id (" + settings.UserID.String() + ")",
			StoredAt:          settings.KeyStoredAt,
			LastUsedAt:        settings.KeyLastUsedAt,
		}
	}
	return view
}

// Get returns the user's settings for display.
func (s *AssistantSettingsService) Get(userID uuid.UUID) (*AssistantSettingsView, error) {
	settings, err := s.load(userID)
	if err != nil {
		return nil, err
	}
	return s.view(settings), nil
}

func wipeKey(settings *models.AssistantSettings) {
	settings.KeyCiphertext, settings.KeyNonce = nil, nil
	settings.KeyVersion, settings.KeyHint = 0, ""
	settings.KeyStoredAt, settings.KeyLastUsedAt = nil, nil
}

// Update applies the fields that are set and returns the new view.
func (s *AssistantSettingsService) Update(userID uuid.UUID, in UpdateAssistantSettingsInput) (*AssistantSettingsView, error) {
	if !s.available {
		return nil, ErrAssistantUnavailable
	}
	settings, err := s.load(userID)
	if err != nil {
		return nil, err
	}
	newKey := ""
	if in.APIKey != nil {
		newKey = strings.TrimSpace(*in.APIKey)
		if len(newKey) > maxProviderKeyLength || strings.ContainsAny(newKey, " \t\r\n") {
			return nil, fmt.Errorf("%w: the API key is not valid", ErrAssistantInput)
		}
	}

	// A key belongs to the endpoint it was entered for. Whenever the provider
	// or the endpoint changes, the stored key is dropped unless a new one comes
	// with the same request, so it can never be sent somewhere else.
	destinationChanged := false

	if in.Provider != nil {
		provider := strings.TrimSpace(*in.Provider)
		preset, ok := llm.PresetByID(provider)
		if !ok {
			return nil, fmt.Errorf("%w: unknown provider %q", ErrAssistantInput, provider)
		}
		if provider != settings.Provider {
			destinationChanged = true
			settings.Provider = provider
			settings.Model = preset.DefaultModel
			settings.BaseURL = ""
			// Suggest the preset's address only where this instance may call it.
			if preset.CustomBaseURL && preset.BaseURL != "" {
				if suggested, err := llm.ValidateBaseURL(preset.BaseURL, s.allowPrivate); err == nil {
					settings.BaseURL = suggested
				}
			}
		}
	}
	preset, hasProvider := llm.PresetByID(settings.Provider)

	if in.BaseURL != nil && hasProvider {
		requested := strings.TrimSpace(*in.BaseURL)
		if !preset.CustomBaseURL {
			// Fixed providers always use their own endpoint.
			requested = ""
		}
		if requested != "" {
			normalised, err := llm.ValidateBaseURL(requested, s.allowPrivate)
			if err != nil {
				return nil, fmt.Errorf("%w: %s", ErrAssistantInput, err.Error())
			}
			requested = normalised
		}
		if requested != settings.BaseURL {
			destinationChanged = true
			settings.BaseURL = requested
		}
	}
	if in.Model != nil {
		model := strings.TrimSpace(*in.Model)
		if len(model) > maxModelNameLength {
			return nil, fmt.Errorf("%w: the model name is too long", ErrAssistantInput)
		}
		settings.Model = model
	}

	keyDropped := destinationChanged && newKey == "" && len(settings.KeyCiphertext) > 0
	if destinationChanged && newKey == "" {
		wipeKey(settings)
	}
	if newKey != "" {
		if !hasProvider {
			return nil, fmt.Errorf("%w: choose a provider before entering a key", ErrAssistantInput)
		}
		ciphertext, nonce, version, err := s.keyring.Seal([]byte(newKey), keyAAD(userID))
		if err != nil {
			return nil, err
		}
		now := time.Now()
		settings.KeyCiphertext, settings.KeyNonce, settings.KeyVersion = ciphertext, nonce, version
		settings.KeyStoredAt, settings.KeyLastUsedAt = &now, nil
		settings.KeyHint = ""
		if len(newKey) >= 12 {
			settings.KeyHint = newKey[len(newKey)-4:]
		}
	}
	if in.Enabled != nil {
		settings.Enabled = *in.Enabled
	}

	if err := s.db.Save(settings).Error; err != nil {
		return nil, err
	}
	// The audit log records that a key was stored or removed, never the key.
	if newKey != "" {
		RecordEvent(s.db, &userID, "assistant.key_stored", map[string]any{"provider": settings.Provider})
	}
	if keyDropped {
		RecordEvent(s.db, &userID, "assistant.key_deleted", map[string]any{"reason": "provider or endpoint changed"})
	}
	return s.view(settings), nil
}

// DeleteKey removes the stored key and keeps the other settings.
func (s *AssistantSettingsService) DeleteKey(userID uuid.UUID) (*AssistantSettingsView, error) {
	settings, err := s.load(userID)
	if err != nil {
		return nil, err
	}
	hadKey := len(settings.KeyCiphertext) > 0
	wipeKey(settings)
	if err := s.db.Save(settings).Error; err != nil {
		return nil, err
	}
	if hadKey {
		RecordEvent(s.db, &userID, "assistant.key_deleted", map[string]any{"reason": "deleted by the user"})
	}
	return s.view(settings), nil
}

// Reset removes the user's assistant settings and key entirely.
func (s *AssistantSettingsService) Reset(userID uuid.UUID) error {
	return s.db.Where("user_id = ?", userID).Delete(&models.AssistantSettings{}).Error
}

// ResolveCredentials returns the configuration with the decrypted key, for one
// provider call. The caller must drop the result when the call is done.
func (s *AssistantSettingsService) ResolveCredentials(userID uuid.UUID) (*AssistantCredentials, error) {
	return s.resolve(userID, true)
}

// ResolveCredentialsForTest is ResolveCredentials for checking a key and
// listing models: the assistant need not be switched on or have a model yet.
func (s *AssistantSettingsService) ResolveCredentialsForTest(userID uuid.UUID) (*AssistantCredentials, error) {
	return s.resolve(userID, false)
}

func (s *AssistantSettingsService) resolve(userID uuid.UUID, forChat bool) (*AssistantCredentials, error) {
	if !s.available {
		return nil, ErrAssistantUnavailable
	}
	settings, err := s.load(userID)
	if err != nil {
		return nil, err
	}
	if forChat && !settings.Enabled {
		return nil, ErrAssistantDisabled
	}
	preset, ok := llm.PresetByID(settings.Provider)
	if !ok || (forChat && strings.TrimSpace(settings.Model) == "") {
		return nil, ErrAssistantNotConfigured
	}
	credentials := &AssistantCredentials{Provider: settings.Provider, Model: settings.Model, BaseURL: settings.BaseURL}
	if len(settings.KeyCiphertext) > 0 {
		plaintext, err := s.keyring.Open(settings.KeyCiphertext, settings.KeyNonce, settings.KeyVersion, keyAAD(userID))
		if err != nil {
			return nil, ErrAssistantKeyUnusable
		}
		credentials.APIKey = string(plaintext)
		now := time.Now()
		if settings.KeyLastUsedAt == nil || now.Sub(*settings.KeyLastUsedAt) >= time.Minute {
			_ = s.db.Model(&models.AssistantSettings{}).Where("user_id = ?", userID).Update("key_last_used_at", now).Error
		}
	} else if preset.KeyRequired {
		return nil, ErrAssistantNotConfigured
	}
	if preset.CustomBaseURL {
		// Enforced again at use: the instance's policy may have changed since it was saved.
		if _, err := llm.ValidateBaseURL(credentials.BaseURL, s.allowPrivate); err != nil {
			return nil, fmt.Errorf("%w: %s", ErrAssistantNotConfigured, err.Error())
		}
	} else {
		credentials.BaseURL = ""
	}
	return credentials, nil
}

// HTTPClient returns the client provider calls must use on this instance: it
// refuses private addresses unless the instance allows them.
func (s *AssistantSettingsService) HTTPClient() *http.Client {
	return llm.SafeHTTPClient(s.allowPrivate)
}
