package services

import (
	"encoding/json"
	"errors"

	"github.com/Butterski/homelab-builder/backend/internal/models"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type BuildService struct {
	db *gorm.DB
}

func NewBuildService(db *gorm.DB) *BuildService {
	return &BuildService{db: db}
}

func (s *BuildService) Create(userID uuid.UUID, name, data, thumbnail string) (*models.Build, error) {
	build := &models.Build{
		UserID:    userID,
		Name:      name,
		Data:      data,
		Thumbnail: thumbnail,
	}
	result := s.db.Create(build)
	return build, result.Error
}

func (s *BuildService) Update(buildID uuid.UUID, userID uuid.UUID, name, data, thumbnail string) (*models.Build, error) {
	var build models.Build
	if err := s.db.First(&build, "id = ?", buildID).Error; err != nil {
		return nil, err
	}

	if build.UserID != userID {
		return nil, errors.New("unauthorized")
	}

	build.Name = name
	build.Data = data
	if thumbnail != "" {
		build.Thumbnail = thumbnail
	}

	// Transaction to update build AND sync relational data
	err := s.db.Transaction(func(tx *gorm.DB) error {
		if err := tx.Save(&build).Error; err != nil {
			return err
		}

		// Sync JSON data to Relational Tables
		// 1. Delete existing nodes/edges/services for this build (simplest strategy for now)
		//    In a real prod app, we might want diffing, but full replace is safer for consistency here.
		//    Cascading delete should handle VMs and ServiceInstances if configured?
		//    Let's check models. If OnDelete:CASCADE is set.
		//    If not, we must delete manually.

		// Manual cleanup to be safe
		if err := tx.Where("build_id = ?", build.ID).Delete(&models.Edge{}).Error; err != nil {
			return err
		}
		if err := tx.Where("build_id = ?", build.ID).Delete(&models.ServiceInstance{}).Error; err != nil {
			return err
		}
		// VMs cascade with Node usually, but GORM needs to know.
		// Let's assume we delete Nodes and their VMs go with them or we delete them first.
		if err := tx.Where("node_id IN (?)", tx.Model(&models.Node{}).Select("id").Where("build_id = ?", build.ID)).Delete(&models.VirtualMachine{}).Error; err != nil {
			return err
		}
		if err := tx.Where("build_id = ?", build.ID).Delete(&models.Node{}).Error; err != nil {
			return err
		}

		// 2. Re-insert from JSON
		// We reuse the migration logic, but we need to parse date first.
		// NOTE: migrateLegacyData expects a *models.Build with .Data set.
		// But it runs on s.db.Transaction... we are ALREADY in a transaction.
		// We need to extract the parsing/inserting logic to a method that accepts a TX.

		return s.syncDataFromJSON(tx, &build)
	})

	if err != nil {
		return nil, err
	}

	return &build, nil
}

func (s *BuildService) syncDataFromJSON(tx *gorm.DB, build *models.Build) error {
	var data LegacyBuildData
	if err := json.Unmarshal([]byte(build.Data), &data); err != nil {
		return err
	}

	idMap := make(map[string]uuid.UUID)

	// 1. Nodes
	for _, ln := range data.HardwareNodes {
		detailsJSON, _ := json.Marshal(ln.Details)
		uid := uuid.New()
		idMap[ln.ID] = uid

		node := models.Node{
			ID:      uid,
			BuildID: build.ID,
			Type:    ln.Type,
			Name:    ln.Name,
			X:       ln.X,
			Y:       ln.Y,
			IP:      ln.IP, // Persist IP from frontend if present (or generated by backend previously)
			Details: string(detailsJSON),
		}
		if err := tx.Create(&node).Error; err != nil {
			return err
		}

		// 1.1 VMs
		for _, vm := range ln.VMs {
			vModel := models.VirtualMachine{
				ID:       uuid.New(),
				NodeID:   uid,
				Name:     vm.Name,
				Type:     vm.Type,
				IP:       vm.IP,
				OS:       vm.OS,
				CPUCores: vm.CPUCores,
				RAMMB:    vm.RAMMB,
				Status:   vm.Status,
			}
			if err := tx.Create(&vModel).Error; err != nil {
				return err
			}
		}
	}

	// 2. Edges
	for _, le := range data.Edges {
		sourceUUID, ok1 := idMap[le.Source]
		targetUUID, ok2 := idMap[le.Target]

		if ok1 && ok2 {
			edge := models.Edge{
				BuildID:      build.ID,
				SourceNodeID: sourceUUID,
				TargetNodeID: targetUUID,
				Type:         "ethernet",
			}
			if err := tx.Create(&edge).Error; err != nil {
				return err
			}
		}
	}

	// 3. Services
	for _, ls := range data.Services {
		catalogID, err := uuid.Parse(ls.ID)
		if err == nil {
			svc := models.ServiceInstance{
				BuildID:          build.ID,
				CatalogServiceID: catalogID,
				Name:             ls.Name,
				Status:           "stopped",
			}
			if err := tx.Create(&svc).Error; err != nil {
				return err
			}
		}
	}

	return nil
}

func (s *BuildService) GetByID(buildID uuid.UUID) (*models.Build, error) {
	var build models.Build
	if err := s.db.Preload("User").Preload("Nodes").Preload("Nodes.VirtualMachines").Preload("Edges").Preload("Nodes.ServiceInstances").First(&build, "id = ?", buildID).Error; err != nil {
		return nil, err
	}

	// Lazy Migration: If we have Data but no Nodes, parse and migrate
	if build.Data != "" && build.Data != "{}" && len(build.Nodes) == 0 {
		if err := s.migrateLegacyData(&build); err != nil {
			// Log error but don't fail the request, return legacy data
			// fmt.Printf("Migration failed: %v\n", err)
		} else {
			// Re-fetch to get the new relations
			_ = s.db.Preload("User").Preload("Nodes").Preload("Nodes.VirtualMachines").Preload("Edges").Preload("Nodes.ServiceInstances").First(&build, "id = ?", buildID)
		}
	}

	return &build, nil
}

// Legacy structures for parsing JSON blob
type LegacyBuildData struct {
	HardwareNodes []LegacyNode    `json:"hardwareNodes"`
	Edges         []LegacyEdge    `json:"edges"`
	Services      []LegacyService `json:"selectedServices"`
}

type LegacyNode struct {
	ID      string     `json:"id"`
	Type    string     `json:"type"`
	Name    string     `json:"name"`
	X       float64    `json:"x"`
	Y       float64    `json:"y"`
	IP      string     `json:"ip"`
	Details any        `json:"details"`
	VMs     []LegacyVM `json:"vms"`
}

type LegacyVM struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Type     string `json:"type"`
	IP       string `json:"ip"`
	OS       string `json:"os"`
	CPUCores int    `json:"cpu_cores"`
	RAMMB    int    `json:"ram_mb"`
	Status   string `json:"status"`
}

type LegacyEdge struct {
	ID     string `json:"id"`
	Source string `json:"source"`
	Target string `json:"target"`
}

type LegacyService struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (s *BuildService) migrateLegacyData(build *models.Build) error {
	return s.db.Transaction(func(tx *gorm.DB) error {
		return s.syncDataFromJSON(tx, build)
	})
}

func (s *BuildService) ListByUser(userID uuid.UUID) ([]models.Build, error) {
	var builds []models.Build
	// Select only metadata, not the huge Data blob for the list view
	if err := s.db.Select("id, user_id, name, thumbnail, created_at, updated_at").Where("user_id = ?", userID).Order("updated_at desc").Find(&builds).Error; err != nil {
		return nil, err
	}
	return builds, nil
}

func (s *BuildService) Delete(buildID uuid.UUID, userID uuid.UUID) error {
	result := s.db.Where("id = ? AND user_id = ?", buildID, userID).Delete(&models.Build{})
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return errors.New("build not found or unauthorized")
	}
	return nil
}
